version: '3.8'
services:
    app:
        build: .
        ports:
        - "6999:6999"
        depends_on:
        - mongodb
        environment:
        MONGO_URI: mongodb://mongodb:27017/alumnos_dam

    mongodb:
        image: mongo:latest
        ports:
        - "27017:27017"
  